// Generated by CoffeeScript 1.6.3
Router.configure({
  layout: 'layout',
  notFoundTemplate: 'errors404',
  loadingTemplate: 'loading',
  before: function() {
    if (Meteor.user() || _.include(['home', 'postsNew'], this.context.route.name)) {
      return;
    }
    if (Meteor.loggingIn()) {
      return this.render('loading');
    } else {
      this.render('accessDenied');
      return this.stop();
    }
  }
});

Router.map(function() {
  this.route('home', {
    path: '/'
  });
  this.route('postsNew', {
    template: 'postsEdit',
    path: '/posts/new'
  });
  this.route('postsEdit', {
    path: '/posts/:_id/edit',
    data: function() {
      return Post.find(this.params._id);
    }
  });
  this.route('postsShow', {
    path: '/posts/:_id',
    data: function() {
      return Post.find(this.params._id);
    }
  });
  this.route('usersShow', {
    path: '/users/:_id',
    waitOn: function() {
      return Meteor.subscribe('user', this.params._id);
    },
    data: function() {
      return Meteor.users.findOne(this.params._id);
    }
  });
  this.route('postsIndex', {
    path: '/posts'
  });
  return this.route('loading', {
    path: '/loading'
  });
});

/*
//@ sourceMappingURL=routes.map
*/
