// Generated by CoffeeScript 1.6.3
Template.postsEdit.events({
  submit: function(e) {
    var url;
    e.preventDefault();
    url = $(e.target).find('[name=url]').val();
    return Meteor.call('postsCreate', {
      url: url
    }, function(error, id) {
      if (error) {
        return alert(error.reason);
      }
      return Router.go('postsIndex');
    });
  }
});

/*
//@ sourceMappingURL=edit.map
*/
